name: Build and Zip

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.1'  

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Create zip
      run: |
        zip -r nextjs-app.zip .next

    - name: Upload zip artifact
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-app
        path: nextjs-app.zip
