name: Export and Create Zip  
on:  
  push:  
    branches:  
      - master  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Checkout code  
      uses: actions/checkout@v2  
    - name: Install dependencies and build  
      run: |  
        npm install  
        npm run build  
    - name: Create zip file  
      run: |  
        zip -r repo.zip out/
        ls -l repo.zip  
    - name: Upload zip file as artifact  
      uses: actions/upload-artifact@v2  
      with:  
        name: zipped-repo  
        path: repo.zip
