name: Build and Zip

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.1'  

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npx next build 


    - name: Create zip file  
      run: |  
        zip -r repo.zip out/
          
    - name: Upload zip file as artifact  
      uses: actions/upload-artifact@v2  
      with:  
        name: zipped-repo  
        path: repo.zip
