name: Export and Create Zip

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Zip 'out' folder
  if: success()  # Only run if previous steps were successful
  run: |
    if [ -d "out" ]; then
      zip -r out.zip out
    else
      echo "'out' folder not found."
    fi

