name: Build and Zip

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.1'  

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Create artifacts directory
      run: mkdir -p artifacts/builds

    - name: Zip build folder
      run: zip -r artifacts/builds/build.zip out
